#!/bin/sh
export PDFTAILOR_DIR="/Users/ted/dc/pdftailor"
java -cp $PDFTAILOR_DIR/jars/itextpdf-5.3.4.jar:$PDFTAILOR_DIR/jars/jcommander-1.31-SNAPSHOT.jar:"$PDFTAILOR_DIR/java/src" org.documentcloud.pdftailor.PdfTailor "$@"
