#!/bin/sh
export PDFTAILOR_DIR=$(dirname $0)
java -cp $PDFTAILOR_DIR/jars/itextpdf-5.3.4.jar:$PDFTAILOR_DIR/jars/jcommander-1.31-SNAPSHOT.jar:$PDFTAILOR_DIR/jars/pdftailor.jar org.documentcloud.pdftailor.PdfTailor "$@"
